- name: minikubeのインストール
  block:
  - name: conntrackパッケージのインストール
    apt:
      name:
        - conntrack
  - name: Get DEB architecture
    shell: dpkg --print-architecture
    register: deb_architecture
  - name: minikubeインストール
    apt:
      deb: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_{{ deb_architecture.stdout }}.deb

