- name: minikubeのポートフォワーディング
  block:
  - name: ポートフォワーディングの設定生成
    shell: |
      declare -a dports=("80" "443")
      declare -a destinations=($(minikube service ingress-nginx-controller -n ingress-nginx --url | cut -d "/" -f 3))
      for (( i = 0; i < 2; i++ )) ; do
        sudo iptables -t nat -A PREROUTING -p tcp -i enp0s3 --dport ${dports[$i]} -j DNAT --to-destination ${destinations[$i]}
      done;
    register: port_forwarding_setting
    args:
      executable: /bin/bash
    become: no
