- name: containerdパッケージインストール
  block:
  - name: 必須パッケージインストール
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
  - name: Docker のリポジトリの GPG 鍵を追加
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Add apt repository
    apt_repository:
      repo: "deb [arch=arm64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  - name: containerdパッケージのインストール
    apt:
      name:
        - containerd
  - name: containerdディレクトリの作成
    file:
      path: /etc/containerd
      state: directory
      mode: 0775
  - name: デフォルト設定を作成
    shell: containerd config default > /etc/containerd/config.toml
