- name: 必要な設定の追加
  block:
  - name: 必須モジュールロード用設定ファイルコピー
    ansible.builtin.copy:
      src: ./modules-loaded.d/containerd.conf
      dest: /etc/modules-load.d/containerd.conf
      owner: root
      group: root
      mode: 0755
  - name: overlay のカーネルモジュールを追加
    community.general.modprobe:
      name: overlay
      state: present
  - name: br_netfilter のカーネルモジュールを追加
    community.general.modprobe:
      name: br_netfilter
      state: present
  - name: 必要なカーネルパラメータの設定・設定値永続化
    ansible.builtin.copy:
      src: ./sysctl.d/99-kubernetes-cri.conf
      dest: /etc/sysctl.d/99-kubernetes-cri.conf
      owner: root
      group: root
      mode: 0755

