- name: iptablesがブリッジを通過するトラフィックを処理できるようにする
  block:
  - name: br_netfilter のカーネルモジュールを追加
    community.general.modprobe:
      name: br_netfilter
      state: present
  - name: net.bridge.bridge-nf-call-ip6tables = 1
    sysctl:
      sysctl_file: /etc/sysctl.d/k8s.conf
      name: net.bridge.bridge-nf-call-ip6tables
      value: '1'
  - name: net.bridge.bridge-nf-call-iptables = 1
    sysctl:
      sysctl_file: /etc/sysctl.d/k8s.conf
      name: net.bridge.bridge-nf-call-iptables
      value: '1'
      reload: yes
