- name: iptablesがブリッジを通過するトラフィックを処理できるようにする
  block:
  - name: br_netfilter のカーネルモジュールを追加
    community.general.modprobe:
      name: br_netfilter
      state: present
  - name: br_netfilter 向けの設定ファイルコピー
    ansible.builtin.copy:
      src: ./netfilter/k8s.conf
      dest: /etc/sysctl.d/k8s.conf
      owner: root
      group: root
      mode: 0755
