- name: ポート設定
  block:
  - name: 初期設定ファイルの有無確認
    stat:
      path: /etc/iptables/rules.v4.my
    register: iptable_setting
  - name: iptables の設定ファイルをコピー
    ansible.builtin.copy:
      src: ./iptables/rules.v4
      dest: /etc/iptables/rules.v4.my
      owner: root
      group: root
      mode: 0755
    when: not iptable_setting.stat.exists
  - name: コピーした設定ファイルを適用
    community.general.iptables_state:
      state: restored
      path: /etc/iptables/rules.v4.my
    when: not iptable_setting.stat.exists
