- name: 必要な設定の追加
  block:
  - name: overlay のカーネルモジュールを追加
    community.general.modprobe:
      name: overlay
      state: present
  - name: br_netfilter のカーネルモジュールを追加
    community.general.modprobe:
      name: br_netfilter
      state: present
  - name: net.bridge.bridge-nf-call-iptables = 1
    sysctl:
      sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
      name: net.bridge.bridge-nf-call-iptables
      value: '1'
  - name: net.ipv4.ip_forward = 1
    sysctl:
      sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
      name: net.ipv4.ip_forward
      value: '1'
  - name: net.bridge.bridge-nf-call-ip6tables = 1
    sysctl:
      sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
      name: net.bridge.bridge-nf-call-ip6tables
      value: '1'
      reload: yes

